name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  code-style:
    name: Code style
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup build
        uses: ./.github/actions/setup-build
      - name: Check code style
        run: ./gradlew ktlintCheck
  binary-compatibility:
    name: Binary compatibility
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup build
        uses: ./.github/actions/setup-build
      - name: Check binary compatibility
        run: ./gradlew apiCheck || { exit_code=$?; printf "*** This PR changes the public API. If this change is intentional, run './gradlew apiDump' and commit the new API files. ***"; exit $exit_code; }
  unit-tests:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup build
      uses: ./.github/actions/setup-build
    - name: Run unit tests
      run: ./gradlew testDebugUnitTest
    - name: Display unit test results
      id: test-results
      uses: bitmovin-engineering/action-junit-report@v4
      if: always()
      with:
        check_name: 'Unit tests: Results'
        report_paths: '**/build/test-results/testDebugUnitTest/TEST-*.xml'
